ALTER SESSION SET nls_language = "POLISH";
set linesize 200;
SET CONCAT OFF
$CLS
PROMPT BAZA DANYCH STRAZY POŻARNEJ PROJEKT:
PROMPT 1. CREATE TABLES
PROMPT 2. DROP TABLES
PROMPT 3. INSERT INTO TABLES
PROMPT 4. PRZEŁADOWANIE BAZY
PROMPT 5. SELECT FROM TABLES
PROMPT 6. TWORZENIE WIDOKOW
PROMPT 7. TWORZENIE KURSOROW
PROMPT 8. TWORZENIE WYZWALACZY
PROMPT 9. WYWOLANIE WIDOKOW
PROMPT A. WYWOLANIE KURSOROW
PROMPT B. WYWOLANIE WYZWALACZY
PROMPT 0. QUIT
ACCEPT tmp CHAR FORMAT 'A1' DEFAULT '0' PROMPT '> '
$CLS
PROMPT tmp = &tmp
PROMPT @&tmp\main.sql &tmp
@&tmp\main.sql &tmp
SET CONCAT ON
PROMPT 
PROMPT # ENTER #
PAUSE
@main.sql