$CLS
PROMPT Menu:
PROMPT 1. SELECT * FROM ADRES;
PROMPT 2. SELECT * FROM STANOWISKO;
PROMPT 3. SELECT * FROM ZMIANA;
PROMPT 4. SELECT * FROM SPRZET;
PROMPT 5. SELECT * FROM JEDNOSTKA;
PROMPT 6. SELECT * FROM JURYSDYKCJA;
PROMPT 7. SELECT * FROM RODZAJ;
PROMPT 8. SELECT * FROM POJAZD;
PROMPT 9. SELECT * FROM OSOBA;
PROMPT A. SELECT * FROM PRACOWNIK;
PROMPT B. SELECT * FROM STATUS;
PROMPT C. SELECT * FROM ZGLOSZENIE;
PROMPT D. SELECT * FROM WYPOSAZENIE;
ACCEPT tmp CHAR FORMAT 'A1' DEFAULT '0' PROMPT '> '
$CLS
DEFINE CURR_DIR=&1
PROMPT tmp = &tmp
@&CURR_DIR\&tmp.sql
PROMPT # ENTER #
PAUSE
@main.sql