SET ECHO ON
DROP TABLE adres CASCADE CONSTRAINTS;
DROP TABLE stanowisko CASCADE CONSTRAINTS;
DROP TABLE zmiana CASCADE CONSTRAINTS;
DROP TABLE sprzet CASCADE CONSTRAINTS;
DROP TABLE jednostka CASCADE CONSTRAINTS;
DROP TABLE jurysdykcja CASCADE CONSTRAINTS;
DROP TABLE rodzaj CASCADE CONSTRAINTS;
DROP TABLE pojazd CASCADE CONSTRAINTS;
DROP TABLE wyposazenie CASCADE CONSTRAINTS;
DROP TABLE osoba CASCADE CONSTRAINTS;
DROP TABLE pracownik CASCADE CONSTRAINTS;
DROP TABLE status CASCADE CONSTRAINTS;
DROP TABLE zgloszenie CASCADE CONSTRAINTS;
SET ECHO OFF
